USE 2fa;
CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  2fa_key VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE token_log (
  owner_id INT NOT NULL,
  token VARCHAR(500) NOT NULL
);